# Generated by Django 6.0.3 on 2026-03-22 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectmember',
            options={'verbose_name': 'Project Member'},
        ),
    ]
