# Generated by Django 6.0.3 on 2026-03-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_title', models.CharField(max_length=200)),
                ('submission_category', models.CharField(choices=[('general', 'General'), ('safety', 'Safety'), ('infrastructure', 'Infrastructure'), ('event', 'Event')], max_length=50)),
                ('submission_location', models.CharField(max_length=255)),
                ('submission_description', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
